name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container: lambci/lambda:build-nodejs12.x
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and build
        run: |
          npm ci
          npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ncc-build
          path: dist/

  test:
    runs-on: ubuntu-latest
    container: lambci/lambda:build-nodejs12.x
    needs: build
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: ncc-build
      - name: Test ncc build
        run: |
          node dist/index.js
      - name: Upload Result
          uses: actions/upload-artifact@v2
          with:
            name: image
            path: dist/out.png
